# @package _global_

# Main medretrieval configuration
defaults:
  - _self_
  - corpus
  - embedding

# Hydra configuration to disable outputs directory
hydra:
  output_subdir: null
  job:
    chdir: false
